# Breakout Room Study Case
Panggil kembali data **house_pricing.csv**. Sebelumnya anda telah melakukan survey mengenai harga rumah dan kondisi rumah. Anda berfikir bahwa anda memerlukan informasi tambahan mengenai luas area, garage area, street, dan neighborhood. Anda telah menyiapkan beberapa pertanyaan mengenai riset anda nantinya. List pertanyaan tersebut seperti berikut :
1. Berapa rata-rata dan standar deviasi dari luas area dan luas garasi yang ditawarkan?
2. Berapakah rata-rata luas area dan garasi berdasarkan neighborhood dan street ?
3. Kira-kira pada kisaran berapakah luas area dan garasi untuk jalan dengan tipe pave?

## Connect Colab dengan Gdrive

In [3]:
from google.colab import drive
drive.mount('/content/gdrive')

## Import Packages

In [4]:
import os
import pandas as pd
import numpy as np
from numpy import random
from numpy import mean
from numpy.random import seed
import scipy.stats as stats
from scipy.stats import ttest_1samp, ttest_ind
import seaborn as sns
import matplotlib.pyplot as plt

## Setting Directory

In [5]:
# im using local env

## Load Data

In [6]:
data = pd.read_csv('house_pricing.csv')
data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

## Pertanyaan 1
Mencari rata-rata dan standar deviasi dari luas area dan luas garasi yang ditawarkan.

In [7]:
stdLotArea = data['LotArea'].std()
meanLotArea = data['LotArea'].mean()
print(f"Standar deviasi garasi berdasarkan data adalah {stdLotArea}")
print(f"Rata-rata luas garasi berdasarkan data adalah {meanLotArea}\n")

stdGarageArea = data['GarageArea'].std()
meanGarageArea = data['GarageArea'].mean()
print(f"Rata-rata luas garasi berdasarkan data adalah {meanGarageArea}")
print(f"Standar deviasi luas garasi berdasarkan data adalah {stdGarageArea}")

Standar deviasi garasi berdasarkan data adalah 9981.26493237915
Rata-rata luas garasi berdasarkan data adalah 10516.828082191782

Rata-rata luas garasi berdasarkan data adalah 472.9801369863014
Standar deviasi luas garasi berdasarkan data adalah 213.80484145338042

## Pertanyaan 2
Mencari rata-rata luas area dan garasi berdasarkan neighborhood dan street

In [8]:
meanLotAreaGarageArea = data.groupby(['Neighborhood', 'Street']).mean()

res = meanLotAreaGarageArea[['LotArea', 'GarageArea']]

res

C:\Users\Tangbim\AppData\Local\Temp\ipykernel_15616\1394994940.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  meanLotAreaGarageArea = data.groupby(['Neighborhood', 'Street']).mean()

                          LotArea  GarageArea
Neighborhood Street
Blmngtn      Pave     3398.176471  502.764706
Blueste      Pave     1625.000000  457.000000
BrDale       Pave     1801.000000  284.000000
BrkSide      Pave     7360.413793  303.241379
ClearCr      Pave    30875.750000  468.428571
CollgCr      Pave     9619.146667  552.580000
Crawfor      Pave    11809.686275  410.078431
Edwards      Grvl    11841.000000    0.000000
             Pave    10202.262626  329.494949
Gilbert      Pave    11379.151899  452.645570
IDOTRR       Grvl    11728.000000  756.000000
             Pave     7789.852941  277.176471
MeadowV      Pave     2324.000000  259.470588
Mitchel      Pave    11624.285714  482.000000
NAmes        Pave    10139.915556  427.062222
NPkVill      Pave     3267.444444  440.000000
NWAmes       Pave    11833.630137  533.520548
NoRidge      Pave    14218.902439  705.926829
NridgHt      Pave    10887.948052  745.753247
OldTown      Pave     8207.061947  382.123894
SWISU        Pave     8127.560000  281.600000
Sawyer       Pave    10459.283784  395.391892
SawyerW      Pave     9923.796610  499.000000
Somerst      Pave     7840.872093  630.627907
StoneBr      Pave    10671.920000  631.520000
Timber       Grvl    99896.500000  762.000000
             Pave    19429.111111  613.805556
Veenker      Pave    15606.000000  546.909091

## Pertanyaan 3
Mencari kisaran luas area dan garasi untuk jalan dengan tipe pave

In [9]:
# kisaran = range 
# rumus kisaran adalah data max - data min
def searchRange (data) :
      rangeKisaran = data.max() - data.min()
      return rangeKisaran

paveLotArea = data[data['Street']=='Pave']['LotArea']
rangeLotArea = searchRange(paveLotArea)

print(f"Jadi kisaran luas area dengan tipe pave adalah {rangeLotArea}")

paveGarageArea = data[data['Street']=='Pave']['GarageArea']
rangeGarageArea = searchRange(paveGarageArea)
print(f"Jadi kisaran luas area garasi dengan tipe pave adalah {rangeGarageArea}")

Jadi kisaran luas area dengan tipe pave adalah 213945
Jadi kisaran luas area garasi dengan tipe pave adalah 1418